name: ci-cd Node.js app
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm install
      # - name: Run test
      #   run: npm test
      - name: Build Docker image
        run: docker build -t tienanhbghd/project-20231:be .
      - name: Login to Docker Hub
        run: docker login -u mjnhmnmm -p phuong2607
      - name: Push Docker image
        run: docker push tienanhbghd/project-20231:be

  # deploy:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Use Node.js
  #       uses: actions/setup-node@master
  #       with:
  #         node-version: "20.x"
  #     - name: Login to Docker Hub
  #       run: docker login -u mjnhmnmm -p phuong2607
  #     - name: Pull Docker image
  #       run: docker pull tienanhbghd/project-20231:be
  #     - name: Start MongoDB container
  #       run: docker run -d --name mongodb mongo
  #     - name: Start Express.js container
  #       run: docker run -d -p 3003:3003 --name express-app --link mongodb tienanhbghd/project-20231:be