name: CI/CD Project-20231
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file
        run: ls -a
        # uses: SpicyPizza/create-envfile@v2.0
        # with:
        #   envkey_PORT: 3003
        #   envkey_MONGODB_URL_DEV: ${{ secrets.MONGODB_URL_DEV }}
        #   envkey_MONGODB_URL_PRODUCT: ${{ secrets.MONGODB_URL_PRODUCT }}
        #   envkey_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        #   envkey_GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        #   envkey_CALLBACK_URL: http://localhost:3003/auth/google/callback
        #   envkey_SECRET_KEY: SECRET_KEY
        #   envkey_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        #   envkey_GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        #   # directory: backend
        #   file_name: README.md
        #   fail_on_empty: false
      # - name : create .envfile
      #   working-directory: backend
      #   run: echo ""
      #   env: 
      #     PORT: 3003
      #     MONGODB_URL_DEV: ${{ secrets.MONGODB_URL_DEV }}
      #     MONGODB_URL_PRODUCT: ${{ secrets.MONGODB_URL_PRODUCT }}
      #     GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      #     GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      #     CALLBACK_URL: http://localhost:3003/auth/google/callback
      #     SECRET_KEY: SECRET_KEY
      #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      #     GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
#       - name: Code Checkout
#         uses: actions/checkout@master

#       - name: Set up Cloud SDK
#         uses: "google-github-actions/setup-gcloud@v1"
#         with:
#           project_id: ${{ secrets.PROJECT_ID }}
#           service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
#           export_default_credentials: true
      
#       - name: Use gcloud CLI
#         run: gcloud info
  
#       - name: Setup Node.js environment
#         uses: actions/setup-node@v4.0.1
#         with:
#           node-version: "20.x"

#       - name: Install dependencies for backend
#         working-directory: backend
#         run: npm install

#       # - name: Install dependencies for frontend
#       #   working-directory: frontend
#       #   run: npm install
      
#       - name: Docker auth          
#         run: |
#           gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet

#       - name: Build Docker image for backend
#         run: docker build -t asia-southeast2-docker.pkg.dev/${{ secrets.PROJECT_ID }}/voz20231/backend:latest . 
#         working-directory: backend
      
#       # - name: Build Docker image for frontend
#       #   run: docker build -t asia-southeast2-docker.pkg.dev/${{ secrets.PROJECT_ID }}/voz20231/frontend:latest . 
#       #   working-directory: frontend

#       - name: Push Docker image for backend to Google Artifact Registry
#         run: docker push asia-southeast2-docker.pkg.dev/${{ secrets.PROJECT_ID }}/voz20231/backend:latest
      
#       # - name: Push Docker image for frontend to Google Artifact Registry
#       #   run: docker push asia-southeast2-docker.pkg.dev/${{ secrets.PROJECT_ID }}/voz20231/frontend:latest
    
#       # - name: Deploy backend to Google Cloud Run
#       #   uses: google-github-actions/deploy-cloudrun@main
#       #   with:
#       #     service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
#       #     image: asia-southeast2-docker.pkg.dev/${{ secrets.PROJECT_ID }}/voz20231/backend:latest
#       #     service: cloudrun-backend-service
#       #     region: asia-southeast2
#       #     project_id: ${{ secrets.PROJECT_ID }}
#       #     args: --allow-unauthenticated
      
#       # - name: Deploy frontend to Google Cloud Run
#       #   uses: google-github-actions/deploy-cloudrun@main
#       #   with:
#       #     service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
#       #     image: asia-southeast2-docker.pkg.dev/${{ secrets.PROJECT_ID }}/voz20231/frontend:latest
#       #     service: cloudrun-frontend-service
#       #     region: asia-southeast2
#       #     project_id: ${{ secrets.PROJECT_ID }}
#       #     args: --allow-unauthenticated
# #   PROJECT_ID: voz-2023-410302
# #   GOOGLE_APPLICATION_CREDENTIALS:
# #  {
# #   "type": "service_account",
# #   "project_id": "voz-2023-410302",
# #   "private_key_id": "193f48ed8cba6549fc19ee0afb4c40a3a276e2ee",
# #   "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDgNH4QMa7e/W7t\n6IbkrMpEGD8Zxel/110bmQ/CthQted/hHgX8cs+JuF4CaHrRz98eCF/FwdWagxa8\nk2hh+wJWc/ZoAgCXEc6AIcOVBmDL5LTi+UJIqKbkrY16/pUEBHJdxjuqZ8Q5enqa\n4AoanaKlwWMTxhasPb0pea0HR4dmNewGglM6x2wiKFDPlrQdnJHC0jbr39nJHhnO\nnmYH6hB3RI9VcPRcXET7W4DkwpQuMnTtkPJrZQgBpwLfuSQJjuJLl27bP+A3GTSK\nRFhWS3jHI/R0A69HlXbBGlYFtg1miymGiA6qkxctKO38qoLLfSXH7PeIuax3ld2+\n54jvsgjZAgMBAAECggEAEAZoeUdX0KvsHRiY5ajdByt1fSXad+8Agmu5BumFPS/g\nGuLOujnJkDYrkAAAQVVahPbDw6qEVjgm7KEbnZ83jk7ZDpuQB7w31owzQshTLFej\nPzLiNDfLv/4Qpfki1QftVbsIwjgK/DG/KCk5x6e7O548Mupebf62sct23NWVva4c\nK7hNHjzq5p2xeOTeKZFqYT2cEjp+SBQHnDVD0DbKqIyc1rBrAjujCysqoqMULL9S\n/W8poFtGyTxb3vZVPu0vtBePxJOTqkDWBV6nXrPl4eaWQZK78ZQu0nzDUitAVOHE\nh/vSHqiwH1uzekr+kdusNv8uIDxhw7v2bicsRczlgQKBgQD94DiPkrEhzvVctU0X\njGBGuA9+hupei8OVLUUQGO6vzdDn+4IVK/1+qBTk4/8CtlznrMMxuR3KC7GAfqFO\nerOLZC6fPSAfPmBsHvT0QgTifRlu2nbNoX4RrQQrJOck6Wq/T+S6qe38d8NITe2Y\nnitapIMvChPBmdWs48cC22vOQQKBgQDiFLgkKyOFoia4cjPpdxEmGlm33tBfZ5T8\nDrn/tW2wBjGZpQmEZC9uf2wqXdLCBYR9tFP8idd49MMu78a77RRHaKUj0+HLHmBe\nmmjw4dvnOZs+T+wHPtIrufLKkqAua+D0tpWo4IHBxly7/oe/IjLJ4sC9gDELuArq\n2ucd39rEmQKBgQCa2rTFZn3jGGDzfqcacQacvFK/I747k1bmXGme6wZUd98wUWpE\nTcPfCNlN0IBRADllGy0o3Dh+cGmB7juoKhHwOVhyyw8X361i5fMWNlrSZ+omgt0q\nipHiaD19r5HKIxJ4xVvIPDSs5cRZCyedCwV40ZYvEB+C3LnILlvKs1prwQKBgCwd\nRuEn2cKVpWCQSDjiFuKMeb07KQW0vImChiCzUjfqvXrxjS3cLrUs//o0XI+na/br\nXQgGDZl4iS17dBfvZumYLcET8xcjUkKjdp6qM7KmtvgtuCyhwXjuy8VjXwYv3rFh\nf0p4pFkfT7EPNYXCMo7aRCm1/dv/iYHSPQ7DQ3jhAoGBAMdwVhIKXccFzPyRlaGJ\ntMEkoQ7EYWLZx/kBAM1nomx8m3rB4mxlCjIuAUgGwZOT3kcUfPDveSqjRUO0a4xX\nV/c359Aj1oCUBOC8oJ/5/gYTZKnu9IhQjaTSjTqkTGTwGqRbAYin3kRyCVng8RZO\nAkiv/0EKWHy3O1se/i61v+Cs\n-----END PRIVATE KEY-----\n",
# #   "client_email": "github-actions@voz-2023-410302.iam.gserviceaccount.com",
# #   "client_id": "105934647555309452757",
# #   "auth_uri": "https://accounts.google.com/o/oauth2/auth",
# #   "token_uri": "https://oauth2.googleapis.com/token",
# #   "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
# #   "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/github-actions%40voz-2023-410302.iam.gserviceaccount.com",
# #   "universe_domain": "googleapis.com"
# # }